version: '3'
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    ports:
      - "5432:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:${RAILS_PORT}"
    depends_on:
      - db