version: '3'
services:
  db:
    image: mdillon/postgis:${POSTGRES_VERSION}
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "${RAILS_PORT}:3000"
    depends_on:
      - db